selling:
  items:
  - ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: TRIPWIRE_HOOK
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Chave
        "},{"bold":true,"italic":false,"color":"gold","text":"Lendária"}],"text":""}'
      lore:
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Uma
        chave especial,"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Para
        uma caixa especial."}],"text":""}'
      enchants:
        THORNS: 1
      ItemFlags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
  - ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: TRIPWIRE_HOOK
    amount: 5
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Chave
        "},{"bold":true,"italic":false,"color":"dark_purple","text":"Epica "},{"bold":true,"italic":false,"color":"red","text":"de
        Minerador"}],"text":""}'
      lore:
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Uma
        chave especial,"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Para
        uma caixa especial."}],"text":""}'
      enchants:
        THORNS: 1
      ItemFlags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
  - ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: TRIPWIRE_HOOK
    amount: 10
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Chave
        "},{"bold":true,"italic":false,"color":"aqua","text":"Rara "},{"bold":true,"italic":false,"color":"red","text":"de
        Minerador"}],"text":""}'
      lore:
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Uma
        chave especial,"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Para
        uma caixa especial."}],"text":""}'
      enchants:
        THORNS: 1
      ItemFlags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
  - ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: TRIPWIRE_HOOK
    amount: 20
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Chave
        "},{"bold":true,"italic":false,"color":"yellow","text":"Básica "},{"bold":true,"italic":false,"color":"red","text":"de
        Minerador"}],"text":""}'
      lore:
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Uma
        chave especial,"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Para
        uma caixa especial."}],"text":""}'
      enchants:
        THORNS: 1
      ItemFlags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
  - ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: TRIPWIRE_HOOK
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"red","text":"Chave
        "},{"bold":true,"italic":false,"color":"aqua","text":"Spawners Básicos"}],"text":""}'
      lore:
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Uma
        chave especial,"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"Para
        uma caixa especial."}],"text":""}'
      enchants:
        THORNS: 1
      ItemFlags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
  commands: []
value: 7
type: product
item:
  name: '§6§lCombo de keys #1'
  glow: true
  lore:
  - §ax1 Keys §6§lLendária
  - §ax5 Keys §5§lEpica
  - §ax10 Keys §b§lRara
  - §ax20 Keys §e§lBásica
  - §ax1 Key §9§lSpawnerB
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: GOLD_NUGGET
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Combo
        de keys #1"}],"text":""}'
      lore:
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"x1
        Keys "},{"bold":true,"italic":false,"color":"gold","text":"Lendária"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"x5
        Keys "},{"bold":true,"italic":false,"color":"dark_purple","text":"Epica"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"x10
        Keys "},{"bold":true,"italic":false,"color":"aqua","text":"Rara"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"x20
        Keys "},{"bold":true,"italic":false,"color":"yellow","text":"Básica"}],"text":""}'
      - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"x1
        Key "},{"bold":true,"italic":false,"color":"blue","text":"SpawnerB"}],"text":""}'
      enchants:
        ARROW_DAMAGE: 1
      ItemFlags:
      - HIDE_ENCHANTS
