type: do-nothing
item:
  name: §aSaída
  glow: false
  lore: []
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 2586
    type: CHEST
    meta:
      ==: ItemMeta
      meta-type: TILE_ENTITY
      display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Saída"}],"text":""}'
      blockMaterial: CHEST
