type: do-nothing
item:
  name: §aResultado
  glow: false
  lore: []
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 2586
    type: TRIPWIRE_HOOK
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Resultado"}],"text":""}'
