type: do-nothing
item:
  name: §bCombustivel tipo A
  glow: false
  lore: []
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 2586
    type: SOUL_CAMPFIRE
    meta:
      ==: ItemMeta
      meta-type: TILE_ENTITY
      display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Combustivel
        tipo A"}],"text":""}'
      blockMaterial: SOUL_CAMPFIRE
