type: do-nothing
item:
  name: §r
  glow: false
  lore: []
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 2584
    type: BLACK_STAINED_GLASS_PANE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"text":""}],"text":""}'
