type: do-nothing
item:
  name: §aCraft
  glow: false
  lore: []
  item:
    ==: org.bukkit.inventory.ItemStack
    v: 2586
    type: BARREL
    meta:
      ==: ItemMeta
      meta-type: TILE_ENTITY
      display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Craft"}],"text":""}'
      blockMaterial: BARREL
